# -*- coding: utf-8 -*-
"""临时测试: LLM 提示词标记 + AI 署名注释移除 + E0000。"""
import text_restore as t

ON = {k: True for k in t.OPTION_ORDER}
OFF_COMMENTS = dict(ON)
OFF_COMMENTS['comments'] = False


def run(raw, enabled=ON):
    r, c, red, green, m = t.convert_text(raw, enabled)
    return r, c


# ---- LLM 提示词标记 ----
r, c = run('回答如下 <|im_start|>user 你好 <|im_end|>')
assert r == '回答如下 user 你好 ', repr(r)
assert c.get('tokens', 0) == 2, c
r, c = run('[INST] 请总结 [\u002fINST]')
assert r == ' 请总结 ', repr(r)
r, c = run('<|system|>你是助手<|endoftext|>')
assert r == '你是助手', repr(r)
# 大小写不敏感
r, c = run('<|IM_START|>x<|IM_END|>')
assert r == 'x', repr(r)
print('LLM tokens OK')

# ---- AI 署名注释 ----
code = 'def f():\n    return 1\n# Generated by AI\n# auto-generated by ai assistant\nx = 2\n'
r, c = run(code, OFF_COMMENTS)
assert r == code, repr(r)   # 默认关闭, 不删除
r, c = run(code, ON)
assert r == 'def f():\n    return 1\nx = 2\n', repr(r)
assert c.get('comments', 0) == 2, c
# 普通注释不删
r, c = run('# this is my comment\n# generated by AI tool\n', ON)
assert r == '# this is my comment\n', repr(r)
print('AI comments OK')

# ---- E0000 标签 ----
r, c = run('a\U000e0000b')
assert r == 'ab', repr(r)
print('E0000 OK')

# ---- 状态/UI ----
import os, tempfile, tkinter as tk
TMP = tempfile.mkdtemp()
t._config_path = lambda: os.path.join(TMP, 'c.json')
root = tk.Tk()
app = t.App(root)
app.lang = 'zh'
app.apply_language()
root.update()
app.input_text.insert('1.0', '<|im_start|> 2024年1月5日 <|im_end|>')
app.do_convert()
root.update()
disp = app.output_text.get('1.0', 'end-1c')
assert disp == ' 2024-01-05 ', repr(disp)
assert '提示词标记 2' in app.status_var.get(), app.status_var.get()
assert '日期时间 1' in app.status_var.get(), app.status_var.get()
# 设置 11 个开关
app.open_settings()
root.update()
def walk(w):
    yield w
    for c in w.winfo_children():
        yield from walk(c)
sws = [w for w in walk(app._settings_win) if isinstance(w, t.Switch)]
assert len(sws) == 11, len(sws)
app._on_lang_change('English')
root.update()
assert app.tr('opt_tokens') == 'LLM tokens'
app._settings_win.destroy()
root.update()
print('UI integration OK')
root.destroy()
print('ALL TESTS PASSED')
